#!/bin/bash

echo starting copy to webapps APP4_HOME....
cp -r /data/tempversion/* /data/wwwroot/APP4
echo starting copy lib to APP4....
cp -r /data/setting/lib/* /data/wwwroot/APP4/WEB-INF/lib
echo starting copy properties to APP4....
cp -r /data/setting/config/* /data/wwwroot/APP4/WEB-INF/classes
echo copy deploy code finished.....
